### PR TITLE
Ctauto 287 cttcm 2480

### PR DESCRIPTION
**Pull request by Gamdie**
This is the testing for CTTCM-2480
It uses an OAP user that is stored in the generalUserInfo.properties file. This user has a llbean card and some coupons if anyone needs one.
For this test, the test case requested that the show coupons link in the payment options page was displayed, but if we are gonna use the same user or not set up any data before the test, then I had to include a condition to not look for the link when it is not available and instead use the coupon that is already selected. You can see this behaviour if you remove the coupon from the payment page and run the test twice. In any case (with coupon already selected or not) the test case should pass.
Also the user will be accumulating items in the bag the more the test runs. So the test allows that and works with or without items previously inserted in the shopping bag.
In the OrderSummary class I used the BigDecimal class to get the prices.

### CODE REVIEW

**Comment by jrdavisllbean** [comment]
@Gamdie I was able to run your test case against Q13 using Chrome and FF. When CTTCM-2480 is executed against Q12, the shopping bag is empty for some reason (see QA12 Test Case). This is not related to your code, I believe this is a bug in R66 QA12. 

The only thing I have noticed so far is the try/catch in the test case is commented out and not used. If the try/catch block is not being used, please delete from the test case.

I will continue to code review against Q13 until the Q12 checkout flow bugs are fixed.

QA12 Test Case
1. Go to http://ecwebq12.llbean.com/.
2. login as oap@pennsylvania.com, password hello123.
3. Click header Shopping Bag link, shopping bag is empty.
4. logoff oap@pennsylvania.com.

5. Repeat above test case at http://ecwebq13.llbean.com/. Shopping Bag contains items.

**Comment by jrdavisllbean** [comment]
@Gamdie In the order summary class, I noticed you are removing the dollar sign and commas. A few weeks ago I created a class named com.llbean.automation.web.utils.CurrencyUtils which contains a method named convertStringToBigDecimal which is similiar to your code. 

If we think CurrencyUtils convertStringToBigDecimal is a good solution then we probably want to replace any str = str.replace(",", ""); calls with CurrencyUtils.convertStringToBigDecimal(string).

Please see below for example.

**existing**

    public BigDecimal parseStringToBD(String str){
          str = str.replace("$", "");
          str = str.replace(",", "");
         return new BigDecimal(str);
    }

**possible new code**

    public BigDecimal parseStringToBD(String str){
          return CurrencyUtils.convertStringToBigDecimal(str);
    }

**CurrencyUtils convertStringToBigDecimal code**

    public static BigDecimal convertStringToBigDecimal(String amount) {

        // Remove all dollar signs and commas. These characters will throw a
        // BigDecimal formatting exception.
        String reformattedAmount = amount.replaceAll("[\\$,]","");

        // Return amount to two decimal places
        return new BigDecimal(reformattedAmount).setScale(2);

    }

**Comment by Gamdie** [comment]
I hate the try catch! But it is to get more "user friendly" errors, so I always comment it to get the full stack trace, but they should be present in the tests.

**Comment by jrdavisllbean** [comment]
LOL, re: the try/catch. I agree, I feel it hides the exception but I understand why it is there.

When testing with Chrome, I noticed line 46 of CTTCM-2480, productPage.selectRandomAttribute() is causing your test to randomly fail (happens against Q12/Q13). When I commented this line out, the test was more stable. 

Once again this is not a result of your code but wanted to mention, I have seen this issue with the BasePageObject.randomSelect method as well. I opened CTAUTO-369 to address.  

            Assert.assertTrue(productPage.isMonogramHelperTextVisible());
                productPage.selectRandomSize();
                //productPage.selectRandomAttribute();
                productPage.selectItemColor();
            //Verifies RIO is updated

Other than the above comments I think we are all set, I will finish testing once the checkout flow in Q12 has been fixed. shar sent a note stating it would be fixed at some point.

**Comment by jrdavisllbean** [comment]
@Gamdie I am not receiving any test failures after your latest commits (601f73a and cf9eac4) using Chrome/FF. This is all set. I will test a little more but plan on merging into master before the automation standup.

**Pull request merged**
