### PR TITLE
Adding functions to handle CTTCM 1636.

### PR DESCRIPTION
**Pull request by didierllbean**
Guys please take a look at this code.

The code includes a data provider to handle the AlphaCodes
Adding a new method to select a different item at pdp
Adding a new config value to handle alpha code, however it is not used so far

Pending tasks for complete the test case
// TODO: At the Add to SB modal click on add button
 // TODO: Validate the product number is correct at the SP page

I think those are already handle by Jamie in his code if not we have to include them

### CODE REVIEW

**Comment by jrdavisllbean** [comment]
Starting now Didier (10:50 EDT)

**Comment by jrdavisllbean** [comment]
Hi Didier, when running CTTCM_1636 against qae13 and llbean.com, I am receiving the exception

 `org.openqa.selenium.WebDriverException: unknown error: Element is not clickable at point (590, 420). Other element would receive the click: <label for="primary-item-label-1314575" class="item-attr-label" onclick="">...</label>` 

The exception is generated when calling CTTCM_1636 line 46 `newPDP.addProductToBag();`. The error is occuring in line 290 of the ProductPage selectItemSet() method.

**Comment by didierllbean** [comment]
Guys I just fix the issue this the TC.

I added a new element to grab the item element and compare if it is selected or not

**Comment by jrdavisllbean** [comment]
Hi @didierllbean  and @ecoronado89, the test executed perfectly when I ran CTTCM_1636 against qae12, qa13 and llbean.com.

**Pull request merged**
